CREATE TABLE IF NOT EXISTS CLD_FEEDBACK (
            ID INTEGER NOT NULL AUTO_INCREMENT,
            MESSAGE VARCHAR(2048),
            EMAIL VARCHAR(128),
            CONTACT_NO VARCHAR(20),
	    UUID CHAR(36) NOT NULL,
	    USER_ID VARCHAR(255),
	    TENANT_ID INTEGER,
            TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (ID),
	    UNIQUE (UUID)
);

CREATE TABLE IF NOT EXISTS CLD_FEEDBACK_TAGS (
            ID INTEGER NOT NULL AUTO_INCREMENT,
            TAG VARCHAR(255),
            PRIMARY KEY (ID),
	    UNIQUE (TAG),
);

CREATE TABLE IF NOT EXISTS CLD_FEEDBACK_TAG_MAPPINGS (
	    ID INTEGER NOT NULL AUTO_INCREMENT,
            FEEDBACK_ID INTEGER NOT NULL,
	    TAG_ID INTEGER NOT NULL,
	    PRIMARY KEY (ID),
            UNIQUE (FEEDBACK_ID,TAG_ID),
            FOREIGN KEY (FEEDBACK_ID) REFERENCES CLD_FEEDBACK(ID) ON DELETE CASCADE,
	    FOREIGN KEY (TAG_ID) REFERENCES CLD_FEEDBACK_TAGS(ID) ON DELETE CASCADE
);
