CREATE TABLE IF NOT EXISTS CLD_FEEDBACK (
            ID INTEGER NOT NULL AUTO_INCREMENT,
            MESSAGE TEXT,
            EMAIL VARCHAR(128),
            CONTACT_NO VARCHAR(20),
	    UUID CHAR(36) NOT NULL,
            TIME_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (ID),
	    UNIQUE (UUID)
);

CREATE TABLE IF NOT EXISTS CLD_FEEDBACK_TAGS (
	    ID INTEGER NOT NULL AUTO_INCREMENT,
            FEEDBACK_ID INTEGER NOT NULL,
            TAG VARCHAR(128) NOT NULL,
	    PRIMARY KEY (ID),
            UNIQUE (FEEDBACK_ID,TAG),
            FOREIGN KEY (FEEDBACK_ID) REFERENCES CLD_FEEDBACK(ID) ON DELETE CASCADE
);